export const portfolioItems = [
  {
    slug: 'smart-tv',
    title: 'Smart TV',
    category: 'Mobile App Development',
    industry: 'Entertainment',
    technology: 'Flutter',
    country: 'United States',
    description: 'A comprehensive Smart TV application built with Flutter, delivering seamless entertainment experiences across multiple platforms.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-2.jpg',
  },
  {
    slug: 'golf-car',
    title: 'Golf Car',
    category: 'Mobile App Development',
    industry: 'Entertainment',
    technology: 'Flutter',
    country: 'United States',
    description: 'An innovative golf cart management and booking application developed with Flutter for enhanced golf course experiences.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-3.jpg',
  },
  {
    slug: 'swyftpro',
    title: 'SwyftPRO',
    category: 'Mobile App Development',
    industry: 'Entertainment',
    technology: 'Flutter',
    country: 'United States',
    description: 'A professional-grade entertainment platform built with Flutter, offering advanced features for content creators and viewers.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-4.jpg',
  },
  {
    slug: 'casacharge',
    title: 'CasaCharge',
    category: 'Mobile App Development',
    industry: 'Entertainment',
    technology: 'Flutter',
    country: 'United States',
    description: 'A smart charging solution app for entertainment devices, developed with Flutter to provide seamless power management.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-5.jpg',
  },
  {
    slug: 'mobile-application-design',
    title: 'Mobile Application Design',
    category: 'Software Development',
    industry: 'Technology',
    technology: 'React Native',
    country: 'United States',
    description: 'Comprehensive mobile application design and development services for various industries.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-6.jpg',
  },
  {
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    category: 'UI/UX Design',
    industry: 'Technology',
    technology: 'Design',
    country: 'United States',
    description: 'Professional UI/UX design services creating intuitive and engaging user experiences.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-7.jpg',
  },
  {
    slug: 'contemporary-art',
    title: 'Contemporary Art',
    category: 'UI/UX Design',
    industry: 'Arts',
    technology: 'Web Design',
    country: 'United States',
    description: 'Digital art platform showcasing contemporary works with modern web design principles.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-2.jpg',
  },
  {
    slug: 'app-for-rent-a-car',
    title: 'App For Rent A Car',
    category: 'Software Development',
    industry: 'Transportation',
    technology: 'React Native',
    country: 'United States',
    description: 'Complete car rental application with booking, payment, and management features.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-3.jpg',
  },
  {
    slug: 'business-analysis',
    title: 'Business Analysis',
    category: 'Business',
    industry: 'Consulting',
    technology: 'Analytics',
    country: 'United States',
    description: 'Comprehensive business analysis and consulting services for digital transformation.',
    cover: '/image/section/project-details-1.jpg',
    thumb: '/image/project-item/project-item-4.jpg',
  },
]


